import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./_ui/globals.css";
import Header from "./_components/Header/Header";
import ReactQueryProvider from "@/app/Utils/ReactQueryProvider";
import { CostsProvider } from "./Context/costContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Klirr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          <ReactQueryProvider>
            <CostsProvider>{children}</CostsProvider>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
